spring.application.name=spring-boot-app
spring.profiles.default=dev
spring.threads.virtual.enabled=true

server.port=${SERVER_PORT:8080}
server.shutdown=graceful

app.name=${APP_NAME:${spring.application.name}}
app.version=${APP_VERSION:0.1.0}
app.environment=${APP_ENV:local}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

