listen_addresses = '*'
port = 5432
timezone = 'Asia/Seoul'
log_timezone = 'Asia/Seoul'

max_connections = 100
shared_buffers = 128MB

logging_collector = on
log_statement = 'none'
log_min_duration_statement = 1000
log_line_prefix = '%m [%p] %q%u@%d '
