name: Semantic PR

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: semantic-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  semantic-pr:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - name: Validate semantic pull request title
        uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            init
            feat
            fix
            build
            chore
            ci
            docs
            style
            refactor
            test
            perf
            revert
            release
          requireScope: false
