FROM python:3.12-alpine
RUN apk update && apk upgrade

# 패키지 업데이트 및 의존성 설치
RUN apk add --no-cache pkgconfig \
                       gcc \
                       openldap \
                       libcurl \
                       gpgme-dev \
                       libc-dev \
                       python3-dev \ 
                       jpeg-dev \
                       zlib-dev \
                       && rm -rf /var/cache/apk/*

# 작업 디렉토리 설정
WORKDIR /fastapi-app
COPY requirements.txt ./
COPY entrypoint.sh ./
COPY . .

# 의존성 설치
RUN pip install --no-cache-dir -r requirements.txt

# 실행 권한 부여 (필요한 경우)
RUN chmod +x entrypoint.sh

ENTRYPOINT ["sh", "./entrypoint.sh"]